/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as OrganizationDepartmentsRouteImport } from './routes/organization.departments'
import { Route as OrganizationDirectoryRouteImport } from './routes/organization.directory'
import { Route as OrganizationEntityRouteImport } from './routes/organization.entity'
import { Route as OrganizationRolesRouteImport } from './routes/organization.roles'
import { Route as OrganizationStructureRouteImport } from './routes/organization.structure'
import { Route as OrganizationEmployeesIndexRouteImport } from './routes/organization.employees.index'
import { Route as OrganizationEmployeesEmployeeIdRouteImport } from './routes/organization.employees.$employeeId'
import { Route as OrganizationRolesIndexRouteImport } from './routes/organization.roles.index'
import { Route as OrganizationRolesRoleIdRouteImport } from './routes/organization.roles.$roleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationDepartmentsRoute = OrganizationDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationDirectoryRoute = OrganizationDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationEntityRoute = OrganizationEntityRouteImport.update({
  id: '/entity',
  path: '/entity',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationRolesRoute = OrganizationRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationStructureRoute = OrganizationStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationEmployeesIndexRoute =
  OrganizationEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => OrganizationRoute,
  } as any)
const OrganizationEmployeesEmployeeIdRoute =
  OrganizationEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => OrganizationRoute,
  } as any)
const OrganizationRolesIndexRoute = OrganizationRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRolesRoute,
} as any)
const OrganizationRolesRoleIdRoute = OrganizationRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => OrganizationRolesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/organization/departments': typeof OrganizationDepartmentsRoute
  '/organization/directory': typeof OrganizationDirectoryRoute
  '/organization/entity': typeof OrganizationEntityRoute
  '/organization/roles': typeof OrganizationRolesRouteWithChildren
  '/organization/structure': typeof OrganizationStructureRoute
  '/organization/': typeof OrganizationIndexRoute
  '/organization/employees/$employeeId': typeof OrganizationEmployeesEmployeeIdRoute
  '/organization/roles/$roleId': typeof OrganizationRolesRoleIdRoute
  '/organization/employees/': typeof OrganizationEmployeesIndexRoute
  '/organization/roles/': typeof OrganizationRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organization/departments': typeof OrganizationDepartmentsRoute
  '/organization/directory': typeof OrganizationDirectoryRoute
  '/organization/entity': typeof OrganizationEntityRoute
  '/organization/structure': typeof OrganizationStructureRoute
  '/organization': typeof OrganizationIndexRoute
  '/organization/employees/$employeeId': typeof OrganizationEmployeesEmployeeIdRoute
  '/organization/roles/$roleId': typeof OrganizationRolesRoleIdRoute
  '/organization/employees': typeof OrganizationEmployeesIndexRoute
  '/organization/roles': typeof OrganizationRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/organization/departments': typeof OrganizationDepartmentsRoute
  '/organization/directory': typeof OrganizationDirectoryRoute
  '/organization/entity': typeof OrganizationEntityRoute
  '/organization/roles': typeof OrganizationRolesRouteWithChildren
  '/organization/structure': typeof OrganizationStructureRoute
  '/organization/': typeof OrganizationIndexRoute
  '/organization/employees/$employeeId': typeof OrganizationEmployeesEmployeeIdRoute
  '/organization/roles/$roleId': typeof OrganizationRolesRoleIdRoute
  '/organization/employees/': typeof OrganizationEmployeesIndexRoute
  '/organization/roles/': typeof OrganizationRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/organization'
    | '/organization/departments'
    | '/organization/directory'
    | '/organization/entity'
    | '/organization/roles'
    | '/organization/structure'
    | '/organization/'
    | '/organization/employees/$employeeId'
    | '/organization/roles/$roleId'
    | '/organization/employees/'
    | '/organization/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/organization/departments'
    | '/organization/directory'
    | '/organization/entity'
    | '/organization/structure'
    | '/organization'
    | '/organization/employees/$employeeId'
    | '/organization/roles/$roleId'
    | '/organization/employees'
    | '/organization/roles'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/organization'
    | '/organization/departments'
    | '/organization/directory'
    | '/organization/entity'
    | '/organization/roles'
    | '/organization/structure'
    | '/organization/'
    | '/organization/employees/$employeeId'
    | '/organization/roles/$roleId'
    | '/organization/employees/'
    | '/organization/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrganizationRoute: typeof OrganizationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/departments': {
      id: '/organization/departments'
      path: '/departments'
      fullPath: '/organization/departments'
      preLoaderRoute: typeof OrganizationDepartmentsRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/directory': {
      id: '/organization/directory'
      path: '/directory'
      fullPath: '/organization/directory'
      preLoaderRoute: typeof OrganizationDirectoryRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/entity': {
      id: '/organization/entity'
      path: '/entity'
      fullPath: '/organization/entity'
      preLoaderRoute: typeof OrganizationEntityRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/roles': {
      id: '/organization/roles'
      path: '/roles'
      fullPath: '/organization/roles'
      preLoaderRoute: typeof OrganizationRolesRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/structure': {
      id: '/organization/structure'
      path: '/structure'
      fullPath: '/organization/structure'
      preLoaderRoute: typeof OrganizationStructureRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/employees/': {
      id: '/organization/employees/'
      path: '/employees'
      fullPath: '/organization/employees/'
      preLoaderRoute: typeof OrganizationEmployeesIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/employees/$employeeId': {
      id: '/organization/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/organization/employees/$employeeId'
      preLoaderRoute: typeof OrganizationEmployeesEmployeeIdRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/roles/': {
      id: '/organization/roles/'
      path: '/'
      fullPath: '/organization/roles/'
      preLoaderRoute: typeof OrganizationRolesIndexRouteImport
      parentRoute: typeof OrganizationRolesRoute
    }
    '/organization/roles/$roleId': {
      id: '/organization/roles/$roleId'
      path: '/$roleId'
      fullPath: '/organization/roles/$roleId'
      preLoaderRoute: typeof OrganizationRolesRoleIdRouteImport
      parentRoute: typeof OrganizationRolesRoute
    }
  }
}

interface OrganizationRolesRouteChildren {
  OrganizationRolesRoleIdRoute: typeof OrganizationRolesRoleIdRoute
  OrganizationRolesIndexRoute: typeof OrganizationRolesIndexRoute
}

const OrganizationRolesRouteChildren: OrganizationRolesRouteChildren = {
  OrganizationRolesRoleIdRoute: OrganizationRolesRoleIdRoute,
  OrganizationRolesIndexRoute: OrganizationRolesIndexRoute,
}

const OrganizationRolesRouteWithChildren =
  OrganizationRolesRoute._addFileChildren(OrganizationRolesRouteChildren)

interface OrganizationRouteChildren {
  OrganizationDepartmentsRoute: typeof OrganizationDepartmentsRoute
  OrganizationDirectoryRoute: typeof OrganizationDirectoryRoute
  OrganizationEntityRoute: typeof OrganizationEntityRoute
  OrganizationRolesRoute: typeof OrganizationRolesRouteWithChildren
  OrganizationStructureRoute: typeof OrganizationStructureRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  OrganizationEmployeesEmployeeIdRoute: typeof OrganizationEmployeesEmployeeIdRoute
  OrganizationEmployeesIndexRoute: typeof OrganizationEmployeesIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationDepartmentsRoute: OrganizationDepartmentsRoute,
  OrganizationDirectoryRoute: OrganizationDirectoryRoute,
  OrganizationEntityRoute: OrganizationEntityRoute,
  OrganizationRolesRoute: OrganizationRolesRouteWithChildren,
  OrganizationStructureRoute: OrganizationStructureRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  OrganizationEmployeesEmployeeIdRoute: OrganizationEmployeesEmployeeIdRoute,
  OrganizationEmployeesIndexRoute: OrganizationEmployeesIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrganizationRoute: OrganizationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
